services:
  backend-container:
    build:
      dockerfile: /home/ubuntu/fptest/routes/Dockerfile.be
    ports:
      - "3000:8000"
  
  
  frontend-container:
    build:
      context: .
      dockerfile: /home/ubuntu/fptest/react/Dockerfile.fe
    ports: 
      - "80:3000"
    depends_on: 
      - app-container
